In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from datetime import timedelta

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error


import warnings
warnings.filterwarnings('ignore')

In [25]:
tweets_predictions_tesla=pd.read_csv('tweets_predictions_tesla.csv', index_col='Date')

In [26]:
tweets_predictions_tesla

,tweet_hashtags,tweet_counts,engagement,Adj Close,predict,residuals,Change,Change_sign,res_sign,predict_tweet
Date,,,,,,,,,,
2011-12-02,I made the volume on the Model S go to 11. ...,1,119,2.220000,2.193516,0.026484,NaN,0,1,0
2011-12-23,Model S options are out! Performance in red an...,1,541,1.860000,1.857583,0.002417,0.837838,0,1,1
2012-01-01,Hacked my Tesla charge connector on a small is...,1,491,1.888000,1.916033,-0.028033,1.015054,1,0,0
2012-01-07,Model S Signature series sold out as of today ...,2,134,1.801556,1.818206,-0.016651,0.954214,0,0,0
2012-01-12,The exec conf room at Tesla used to be called ...,1,416,1.883333,1.870362,0.012971,1.045393,1,1,1
...,...,...,...,...,...,...,...,...,...,...
2021-04-12,If you don’t say anything &amp; engage Autopil...,1,3048,233.993332,228.170400,5.822937,1.011994,1,1,0
2021-04-14,Tesla is building up collision repair capabili...,1,29369,244.076660,239.857730,4.218933,1.043092,1,1,0
2021-04-15,Absolutely| True. Ancient times … Had to flip ...,5,66857,246.283340,249.126820,-2.843475,1.009041,1,0,1
2021-04-16,I found some footage of the drive | Stop … In...,5,165555,246.593338,243.509660,3.083679,1.001259,1,1,0
2021-04-17,"I was just there, driving Cybertruck around th...",3,27411,246.593338,245.028630,1.564713,1.000000,1,1,0

In [27]:
tweets_predictions_tesla['new_predicted']=tweets_predictions_tesla['predict_tweet']+tweets_predictions_tesla['predict']

In [28]:
tweets_predictions_tesla = tweets_predictions_tesla.fillna(0)

In [31]:
tweets_predictions_tesla.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1036 entries, 2011-12-02 to 2021-04-17
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tweet_hashtags  1036 non-null   object
 1   tweet_counts    1036 non-null   int64
 2   engagement      1036 non-null   int64
 3   Adj Close       1036 non-null   float64
 4   predict         1036 non-null   float64
 5   residuals       1036 non-null   float64
 6   Change          1036 non-null   float64
 7   Change_sign     1036 non-null   int64
 8   res_sign        1036 non-null   int64
 9   predict_tweet   1036 non-null   int64
 10  new_predicted   1036 non-null   float64
dtypes: float64(5), int64(5), object(1)
memory usage: 97.1+ KB

In [10]:
# calculate root mean squared error
# RMSE between actual and predicted test values
import math
from sklearn.metrics import mean_squared_error

testScore = math.sqrt(mean_squared_error(tweets_predictions_tesla['Adj Close'], tweets_predictions_tesla['new_predicted']))
print('Root Mean Square Error: %.2f RMSE' % (testScore))

Root Mean Square Error: 3.62 RMSE

In [33]:
# R-squared
r2 = r2_score(tweets_predictions_tesla['Adj Close'], tweets_predictions_tesla['new_predicted'])
print('R-squared:', r2)

R-squared: 0.9965026038426437

In [34]:
#Mean Absolute Error (MAE)
mae_test_score = mean_absolute_error(tweets_predictions_tesla['Adj Close'], tweets_predictions_tesla['new_predicted'])

print('Test MAE: ',mae_test_score)

Test MAE:  1.599100965033225

In [35]:
subset = tweets_predictions_tesla[['tweet_hashtags', 'Adj Close', 'predict','predict_tweet','new_predicted']]

In [36]:
subset

,tweet_hashtags,Adj Close,predict,predict_tweet,new_predicted
Date,,,,,
2011-12-02,I made the volume on the Model S go to 11. ...,2.220000,2.193516,0,2.193516
2011-12-23,Model S options are out! Performance in red an...,1.860000,1.857583,1,2.857583
2012-01-01,Hacked my Tesla charge connector on a small is...,1.888000,1.916033,0,1.916033
2012-01-07,Model S Signature series sold out as of today ...,1.801556,1.818206,0,1.818206
2012-01-12,The exec conf room at Tesla used to be called ...,1.883333,1.870362,1,2.870362
...,...,...,...,...,...
2021-04-12,If you don’t say anything &amp; engage Autopil...,233.993332,228.170400,0,228.170400
2021-04-14,Tesla is building up collision repair capabili...,244.076660,239.857730,0,239.857730
2021-04-15,Absolutely| True. Ancient times … Had to flip ...,246.283340,249.126820,1,250.126820
2021-04-16,I found some footage of the drive | Stop … In...,246.593338,243.509660,0,243.509660
2021-04-17,"I was just there, driving Cybertruck around th...",246.593338,245.028630,0,245.028630

In [ ]:
new_names = {'tweet_hashtags': 'Tweets one day before', 'predict': 'Prediction with MLP', 'C': 'Column3'}
df = df.rename(columns=new_names)